# Ansible Inventory for Jenkins Deployment on AWS

[jenkins_master]
# Будет заполнено после запуска Terraform
# jenkins-master ansible_host=<MASTER_PUBLIC_IP> ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/Group2-KeyPair.pem

[jenkins_slave]
# Будет заполнено после запуска Terraform
# jenkins-slave-1 ansible_host=<SLAVE_PUBLIC_IP> ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/Group2-KeyPair.pem

[jenkins:children]
jenkins_master
jenkins_slave

[jenkins:vars]
ansible_python_interpreter=/usr/bin/python3
